steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "echo '$_DOCKERHUB_TOKEN' | docker login -u 'noxzz' --password-stdin && docker build -t docker.io/noxzz/hd-repo:$SHORT_SHA . && docker push docker.io/noxzz/hd-repo:$SHORT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials $_CLUSTER_NAME --zone $_CLUSTER_ZONE --project $PROJECT_ID
        sed -i 's|IMAGE_TAG|$SHORT_SHA|g' k8s/deployment.yaml
        kubectl apply -f k8s/

images:
  - "docker.io/noxzz/hd-repo:$SHORT_SHA"

substitutions:
  _CLUSTER_NAME: "hd-gke-cluster"
  _CLUSTER_ZONE: "australia-southeast1-a"
  _DOCKERHUB_TOKEN: ""

options:
  logging: CLOUD_LOGGING_ONLY
