apiVersion: v1
kind: Service
metadata:
  name: hd-repo-service
  labels:
    app: hd-repo
spec:
  type: LoadBalancer
  selector:
    app: hd-repo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
